### Site metadata ###

title: Jekyll Theme Quickstart Demo
description: "Demonstrate build a template them on GitHub Pages"

github_username: MichaelCurrin

### Build settings ###

url: https://mtearle.github.io
baseurl: /jekyll-theme-quickstart

remote_theme: BioplatformsAustralia/jekyll-theme-bpa

plugins:
  - jekyll-remote-theme

exclude:
  - vendor/
  - README.md
  - Gemfile
  - Gemfile
